version: '3'

### Network Configuration #######################################

services:
  mysqldb:
    container_name: mysqldb
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=simple-api
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password

### Golang Based Services Container ################################

  simpleapi:
    container_name: simpleapi
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app/simpleapi
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - mysqldb
        